#!/bin/bash
#
# Build and run tests for all modules.

function print_module_info() {
  echo
  echo '********************'
  echo "Test $1"
  echo '********************'
  echo
}

function test_module() {
  local module_dir="$1"

  print_module_info "${module_dir}"
  (cd "${module_dir}" && make test)

  if (( $? != 0 )); then
    exit 1
  fi
}

function main() {
  local module_dir

  for module_dir in src/*; do
    if [[ ! -d "${module_dir}" ]]; then
      continue
    fi

    test_module "${module_dir}"
  done
}

main
