name: unit-test
on:
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./scripts/test
